### ISSUE TITLE
compile-goto-error does not open file automatically

### ISSUE THREAD

**Issue by remyferre** [dominikh/go-errcheck.el#4]
Hey Dominik, thanks for this package

When I run go-errcheck-pkg and I want to go to an error in a file, I am asked to enter the file path if this file is not open in my  Emacs yet. Why cannot it open the file automatically when I click on it? The file path is known.

(see minibuffer at the end of the gif)
![demo](http://i.imgur.com/CmDJBQB.gif)

**Comment by dominikh** [comment]
Hi. You cannot open the files automatically, because errcheck is printing paths relative to GOPATH, not to the current working directory. Emacs thus looks in the wrong place, can't find the file, and asks you instead.

Version 1.1.2 of go-errcheck.el makes use of errcheck's new `-abspath` flag, causing it to print absolute paths. This makes the output longer, but on the plus side you can now directly jump to the files.

You will need to update errcheck for this (`go get -u github.com/kisielk/errcheck`)
